# Use Python as base image
FROM python:3.9

# Set working directory
WORKDIR /app

# Copy project files
COPY api_server.py .
COPY node.py .

# Install dependencies
RUN pip install flask docker requests

# Run API server on container startup
CMD ["python", "api_server.py"]
